[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; font-src 'self' fonts.gstatic.com; img-src 'self' https://eqwc.goatcounter.com/count; style-src 'self' fonts.googleapis.com; script-src 'self'; connect-src https://eqwc.goatcounter.com/count"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), battery=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"